"""The offline demo runs the real document workflow on synthetic data with scripted replies."""
import json
import shutil
import socket
import subprocess

import pytest

from careerops import demo
from careerops.store import Store


@pytest.fixture(scope="module")
def result(tmp_path_factory):
    out = tmp_path_factory.mktemp("offline-demo")
    return out, demo.run_demo(out)


def test_roles_and_stages_follow_the_graph(result):
    _, t = result
    assert t["role_sequence"] == ["generator", "red", "blue", "red", "blue", "purple"]
    assert [s["stage"] for s in t["stages"]] == [
        "draft", "evidence", "review", "improvements", "evidence", "review", "improvements", "synthesis", "document"]
    assert t["final_stage"] == "complete"
    assert [c["receipt_key"] for c in t["calls"]] == [
        "a:generation", "a:r0:red", "a:r0:blue", "a:r1:red", "a:r1:blue", "a:purple"]
    # Both reviewers in a round receive the identical frozen packet.
    assert t["calls"][1]["packet_sha256"] == t["calls"][2]["packet_sha256"]
    assert t["calls"][3]["packet_sha256"] == t["calls"][4]["packet_sha256"]
    assert t["calls"][1]["packet_sha256"] != t["calls"][3]["packet_sha256"]


def test_revision_saves_a_child_version_from_an_applied_suggestion(result):
    _, t = result
    first, second = t["materials"]
    assert second["parent_id"] == first["id"] and first["parent_id"] is None
    assert second["cv_text"] != first["cv_text"]
    applied = [s for s in t["suggestions"] if s["status"] == "applied"]
    # The applied finding's evidence sentence is appended once more, under the role.
    added = next(e["text"] for e in demo.EVIDENCE if e["id"] == applied[0]["action"]["evidence_ids"][0])
    assert second["cv_text"].count(added) == first["cv_text"].count(added) + 1
    assert [(s["id"], s["category"], s["validation"]["status"], s["action"]["type"]) for s in applied] == [
        ("1:a:0:red:0", "document_problem", "eligible", "add_evidence")]
    assert t["what_improved"] == ["Add the omitted approved evidence to this role."]


def test_unanchored_finding_is_demoted_to_a_question(result):
    _, t = result
    finding = next(s for s in t["suggestions"] if s["id"] == "1:a:0:red:1")
    assert finding["advert_requirement"] == demo.UNANCHORED_QUOTE
    assert demo.UNANCHORED_QUOTE not in demo.JOB["description"]
    assert finding["category"] == "question"
    assert finding["validation"]["status"] == "needs_verification"
    assert finding["status"] == "needs_answer"
    gap = next(s for s in t["suggestions"] if s["id"] == "1:a:0:blue:0")
    assert gap["category"] == "experience_gap" and gap["advert_requirement"] in demo.JOB["description"]


def test_run_needs_an_answer_and_writes_no_live_receipts(result):
    out, t = result
    assert t["status"] == "needs_answer" and t["error"] is None
    assert t["live_receipts_written"] is False
    assert Store(out / "demo.sqlite3").meta("cv_model_live_receipts") is None
    assert all(r["mocked"] is True and r["provider"] == demo.PROVIDER for r in t["receipts"].values())


def test_pack_is_marked_mocked_and_docx_check_passed(result):
    out, t = result
    final = str(t["materials"][-1]["id"])
    pack = t["application_packs"][final]
    assert pack["mocked"] is True
    assert {d["finding_id"] for d in pack["decisions"]} == {"1:a:1:red:0", "1:a:1:blue:0"}
    assert demo.EVIDENCE[0]["text"] in pack["cover_letter"]["text"]
    check = t["document_checks"][final]
    assert check["status"] == "passed" and check["docx_available"] is True and check["pdf_available"] is False
    assert t["exported_files"] == [f"materials/{final}/application-draft.docx"]
    assert (out / t["exported_files"][0]).is_file()


def test_transcript_is_written_and_labelled(result):
    out, t = result
    saved = json.loads((out / "transcript.json").read_text(encoding="utf-8"))
    assert saved["stable_sha256"] == t["stable_sha256"]
    assert saved["mocked"] is True and saved["synthetic_data"] is True
    assert saved["statement"].startswith("No model was called.")
    assert all(c["packet"] and c["response"] and len(c["schema_sha256"]) == 64 for c in saved["calls"])
    text = (out / "transcript.md").read_text(encoding="utf-8")
    assert "Generated by `python -m careerops.demo`. All data is synthetic. No model was called." in text
    assert str(out) not in text


def test_offline_guard_was_active_for_every_call(result):
    _, t = result
    assert t["offline_guard"]["attempts"] == []
    assert all(c["offline_guard_active"] is True for c in t["calls"])


def test_offline_guard_blocks_processes_and_network_then_restores():
    originals = (subprocess.Popen, subprocess.run, socket.socket.connect, socket.create_connection, shutil.which)
    with demo.offline_guard() as guard:
        for attempt in (lambda: subprocess.run(["true"]), lambda: subprocess.Popen(["true"]),
                        lambda: socket.create_connection(("example.invalid", 80)),
                        lambda: socket.socket().connect(("127.0.0.1", 9)), lambda: shutil.which("soffice")):
            with pytest.raises(demo.OfflineViolation):
                attempt()
        assert len(guard["attempts"]) == 5
    assert (subprocess.Popen, subprocess.run, socket.socket.connect, socket.create_connection, shutil.which) == originals


def test_second_run_is_identical(tmp_path, result):
    _, first = result
    again = demo.run_demo(tmp_path)
    repeated = demo.run_demo(tmp_path)  # rerunning into the same folder starts afresh
    assert again["stable_sha256"] == repeated["stable_sha256"] == first["stable_sha256"]
    assert [c["packet_sha256"] for c in again["calls"]] == [c["packet_sha256"] for c in first["calls"]]


def test_refuses_a_folder_it_did_not_create(tmp_path):
    (tmp_path / "keep.txt").write_text("not demo data", encoding="utf-8")
    with pytest.raises(ValueError, match="not created by this demo"):
        demo.run_demo(tmp_path)
    assert (tmp_path / "keep.txt").read_text(encoding="utf-8") == "not demo data"


def test_command_line_prints_a_short_summary(tmp_path, capsys):
    out = tmp_path / "demo"
    assert demo.main(["--out", str(out)]) == 0
    printed = capsys.readouterr().out
    assert printed.startswith("CareerOps offline demo: synthetic data, scripted replies, no model called.")
    assert "Model-role calls (scripted): generator, red, blue, red, blue, purple" in printed
    assert "Final status: needs_answer" in printed
    assert (out / "transcript.json").is_file() and (out / "transcript.md").is_file()
